name: Build and Release Maalem AlSunnah

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: muslimpack/.github/.github/workflows/flutter_release.yaml@main
    with:
      app_directory: ruqayyah
      package_name: com.hassaneltantawy.ruqayyah
      java_version: '17'
    secrets:
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}